using System.Text;

namespace Ww.Winter.Generator.QueryableFilters;

public static class QueryableFilterRenderer
{
    private static readonly string[] Header =
    [
        "//---------------------------------------------------------------------------------------------------",
        "// <auto-generated>",
        "//     This code was generated by the Ww.Winter source generator.",
        "//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.",
        "// </auto-generated>",
        "//---------------------------------------------------------------------------------------------------",
    ];

    public static (string Content, string HintName) Render(QueryableFilterToGenerate toGenerate)
    {
        var filter = toGenerate.Filter;
        var entity = toGenerate.Entity;

        var sb = new StringBuilder(4 * 1024);
        foreach (var header in Header)
        {
            sb.AppendLine(header);
        }
        sb.AppendLine();
        sb.AppendLine($"using System.Linq;");
        sb.AppendLine($"using {entity.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {filter.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {filter.TypeName}");
        sb.AppendLine($"{{");

        sb.AppendLine($"    public IQueryable<{entity.TypeName}> ApplyFilter(IQueryable<{entity.TypeName}> query)");
        sb.AppendLine($"    {{");
        foreach (var property in filter.Properties)
        {
            var filterProperty = new QueryableFilterPropertyIdentifierParser().Parse(entity, property);
            if (filterProperty is null)
            {
                sb.AppendLine($"        // WARN: Unable to process filter property '{property.PropertyName}' for entity '{entity.TypeName}'");
                continue;
            }
            var entityProperty = filterProperty.Property.PropertyName;

            sb.AppendLine($"        if (this.{property.PropertyName} is not null)");
            sb.AppendLine($"        {{");
            switch (filterProperty!.Comparison)
            {
                case FilterComparison.Equals:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} == this.{property.PropertyName});");
                    break;
                case FilterComparison.NotEquals:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} != this.{property.PropertyName});");
                    break;
                case FilterComparison.GreaterThan:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} > this.{property.PropertyName});");
                    break;
                case FilterComparison.GreaterThanOrEqual:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} >= this.{property.PropertyName});");
                    break;
                case FilterComparison.LessThan:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} < this.{property.PropertyName});");
                    break;
                case FilterComparison.LessThanOrEqual:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty} <= this.{property.PropertyName});");
                    break;
                case FilterComparison.Contains:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty}.Contains(this.{property.PropertyName}));");
                    break;
                case FilterComparison.StartsWith:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty}.StartsWith(this.{property.PropertyName}));");
                    break;
                case FilterComparison.EndsWith:
                    sb.AppendLine($"            query = query.Where(e => e.{entityProperty}.EndsWith(this.{property.PropertyName}));");
                    break;
            }
            sb.AppendLine($"        }}");
        }
        sb.AppendLine();
        sb.AppendLine($"        return query;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        sb.AppendLine($"}}");

        var content = sb.ToString();

        var filename = Helpers.ToSafeFileName(entity.FullyQualifiedTypeName, "QueryableFilters");
        return (content, filename);
    }
}