//---------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Ww.Winter source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

using System.Linq;
using Ww.Winter.Some.Books;

#nullable enable

namespace ;

public partial class QueryBooksFilter
{
    public IQueryable<Book> ApplyFilter(IQueryable<Book> query)
    {
        if (this.TitlePrefix is not null)
        {
            query = query.Where(e => e.Title.StartsWith(this.TitlePrefix));
        }
        if (this.TitleFragment is not null)
        {
            query = query.Where(e => e.Title.Contains(this.TitleFragment));
        }
        if (this.Isbn is not null)
        {
            query = query.Where(e => e.Isbn == this.Isbn);
        }
        if (this.AuthorFragment is not null)
        {
            query = query.Where(e => e.Author.Contains(this.AuthorFragment));
        }
        if (this.CategoryFragment is not null)
        {
            query = query.Where(e => e.Category.Contains(this.CategoryFragment));
        }
        if (this.PageCountFrom is not null)
        {
            query = query.Where(e => e.PageCount >= this.PageCountFrom);
        }
        if (this.PageCountTo is not null)
        {
            query = query.Where(e => e.PageCount <= this.PageCountTo);
        }

        return query;
    }

}
